### ISSUE TITLE
tsd install cleans typings directory using path relative to pwd rather than config file

### ISSUE THREAD

**Issue by SpenceDiNicolantonio** [DefinitelyTyped/tsd#203]
During `tsd install`, typings path is resolved relative to the config file for installation, but relative to execution directory when cleaning.

Say I have the following project structure:
```
app
    source-file-1
    source-file-2
typings
    app
        typing-1
        typing-2
tsd.json
```
with tsd path configured to be `typings/app`.

Executing `tsd install` will cause all files within the `typings/app` directory to be deleted, and then all typings defined in tsd.json will be installed in the `typings/app` directory. This is desired behavior.

If I have this project structure (note tsd.json is no longer at the project root):
```
app
    source-file-1
    source-file-2
typings
    app
        typing-1
        typing-2
    tsd.json
```
with tsd path configured to be `app`

Executing `tsd install --config typings/tsd.json` will install typings defined in tsd.json in the `typings/app` directory, because the installation directory is resolved relative to tsd.json. However, when tsd attempts to clean, it will delete all files in `app` (`source-file-1` and `source-file-2`) rather than in `typings/app`, as it resolves the typings path relative to the directory from which `tsd install` was executed, rather than relative to tsd.json.

**Comment by Diullei** [comment]
Hi @SpenceDiNicolantonio, this issue has been fixed with `tsd@0.6.5-beta`.

Some notes:

Now the `install` command does not cleans the `typings` directory.

The `reinstall` command will remove your custom typings only if you use the `--clean` flag.

To install the beta version:

```
npm install tsd@0.6.5-beta
```

Thanks for reporting this issue.

for more info https://github.com/DefinitelyTyped/tsd/issues/184
