### ISSUE TITLE
definition name

### ISSUE THREAD

**Issue by Reichstetter** [DefinitelyTyped/tsd#206]
Is there some library of correct names?  For example, AngularJS is angular.  I am trying to install googlemaps (query *google* shows it, but tsd install googlemaps --save returns 'Zero Results')

**Comment by Diullei** [comment]
Hi!

The search pattern is always based at the filename by default. For example:

To `AngularJS` we use `tsd query angular` because at [ThefinitelyTyed](https://github.com/borisyankov/DefinitelyTyped/tree/master/angularjs) repository the filename for angular is `angular.d.ts`. `AngularJS` is the directory name. you can use some pattern to search using directory names like `tsd query angularjs/` or `tsd query angular2/`.

To google maps you can use the following search patterns:

```
tsd query googlemaps/ # to search at google maps directory
tsd query google*     # to search all files starting with google
tsd query google.maps # to search exact file name
```

In your case you can install google maps with:

```
tsd install google.maps --save
```

**Comment by Diullei** [comment]
I'll close this issue for now. Please, reopen this issue if you still with problems.
