### ISSUE TITLE
How to install all definition for the project modules?

### ISSUE THREAD

**Issue by chenxizhang** [DefinitelyTyped/tsd#233]
How to install all definition for the project modules? Just like 'npm install' command, without 'tsd install' one by one?

thanks

**Comment by blakeembrey** [comment]
`npm install` works because you've already defined all the dependency. This should currently work too, if you've defined them in `tsd.json`. What you're probably after is something like https://github.com/DefinitelyTyped/tsd/issues/115 (I thought there was a more general issue on `install --implicit`). I'm closing up the alpha of the rewrite now, and this will be the next target.
