### ISSUE TITLE
npm install tsd locally

### ISSUE THREAD

**Issue by micheledisalvatore** [DefinitelyTyped/tsd#239]
Hi guys, 
I'd like to use tsd as project dependency, not as global. 
Installing it as local, it doesn't work.

Any idea? 

Thanks

**Comment by blakeembrey** [comment]
@micheledisalvatore Can you paste an error message or something that indicates it didn't work here? It should work fine using `npm install tsd`.

**Comment by micheledisalvatore** [comment]
These are my steps and my scenario:
```bash
$ npm install tsd
... some output ...

$ tsd
bash: /usr/local/bin/tsd: No such file or directory

$ node ./node_modules/tsd/build/cli.js
>> tsd 0.6.5

$ npm -v
3.3.12

$ node -v
v4.2.1
```

**Comment by blakeembrey** [comment]
@micheledisalvatore That's how locally installed dependencies work? The won't be aliased globally. You can use it in NPM scripts automatically because NPM will set the `PATH` to node modules first, which allows you to do that. Did you need help with something beyond that?

**Comment by micheledisalvatore** [comment]
Usually yes, this is the way that I install locally. I think the problem is in the .bin directory, have you tried by your own?

**Comment by blakeembrey** [comment]
To be honest, you lost me somewhere there. From your snippet, it's working exactly how it's meant to be when you install without `--global`. What is it that's not working properly? 

```
➜  tmp  tsd
zsh: command not found: tsd
➜  tmp  node ./node_modules/.bin/tsd

>> tsd 0.6.5
```

I think you might be confusing a local installation of a module with a global installation. If you want it available in your terminal as a command, you have to install it with `npm install tsd --global`. Otherwise, it's a local dependency and is used as such.

**Comment by wjurmy** [comment]
@blakeembrey fantastico!
