### ISSUE TITLE
tsd query, returns zero results

### ISSUE THREAD

**Issue by abhinavkant** [DefinitelyTyped/tsd#300]
I have tried executing tsd query node --action install --save
or tsd query jquery
or tsd query *
it always returns "zero results"

**Comment by gregonmac** [comment]
Same behaviours

**Comment by AndrewKiri** [comment]
I confirm the same behavior.
![image](https://cloud.githubusercontent.com/assets/13384229/24083064/737826dc-0cd0-11e7-9ccf-b344c6164541.png)

**Comment by AndrewKiri** [comment]
The definitely typed repo has so many projects for which types are written, big part of them are truncated when the github repo is opened. Can it also be a reason why the terminal command returns zero results?

**Comment by itsromiljain** [comment]
Same behavior for me also. 
$tsd install react --save
always returning Zero Results.
Is any one able to resolve it ?

**Comment by gregonmac** [comment]
I use npm install @types ([https://www.npmjs.com/~types](https://www.npmjs.com/~types)) in place of tsd, it's not a solution for the bug but it's a solution for the problem.

**Comment by Bartvds** [comment]
The structure in the DefinitelyTyped repo changed to accommodate @types. This means TSD can't read the index and parse for installables anymore (it depended on the file names but those are all `index` now). It could be a bit of a hassle to make it work correctly (semantics of names etc) with the new repo structure. 

It still *re*installs fine because `tsd.json` is linked against DT commit hashes. 

Since everything is moving to @types anyway it is not a big priority to extend TSD's life, especially since there are various alternatives.

If you are serious about TypeScript you should migrate your project to npm @types soonest because that is the official Microsoft supported way forward.

**Comment by nycdotnet** [comment]
A wild @Bartvds appears!!

**Comment by johnnyreilly** [comment]
Ha!

**Comment by abhinavkant** [comment]
based on the update on TSD repo : 

"DEPRECATED: TSD is deprecated, please use Typings and see this issue for more information."

**Comment by kaisrec** [comment]
**tsd** is deprecated The following steps helped me install the type definitions.
In the application folder
Delete typings folder (if it exists)
Run the following commands

npm init
npm install --save @types/angular
