### ISSUE TITLE
@types/bluebird missing 'Map'

### ISSUE THREAD

**Issue by gpresland** [DefinitelyTyped/tsd#302]
@types/bluebird gives the following error:

```bash
node_modules/@types/bluebird/index.d.ts(623,33): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(623,78): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(810,39): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(810,78): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(813,27): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(813,65): error TS2304: Cannot find name 'Map'.
```

**Comment by gpresland** [comment]
Moved to:

https://github.com/types/npm-bluebird/issues/46

**Comment by nycdotnet** [comment]
Hi - I think you're still in the wrong spot.  This is the repo for a command line tool tsd which is no longer used.  While I'm here, I suspect your issue is that you don't have the right 'lib' setting in your tsconfig.json file.  See here.  https://www.typescriptlang.org/docs/handbook/compiler-options.html  You might need lib "es2015" to get Map.  The lib setting basically lets TypeScript know what is available in your environment.  Hope that helps.  If not, stack overflow is the right place to ask for help as what you're describing above is not a bug in the definition.
